name: Publish

on:
  pull_request:
    types: [closed]
    branches:
      - dev
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true # Condition
    runs-on: ubuntu-latest
    permissions:
      contents: write # for checkout and tag
      pull-requests: write  # for comments
      packages: write # for publish

    steps:
      - name: "Checkout" # Download code from the repository
        uses: actions/checkout@v3 # Public action
        with:
          fetch-depth: 0 # Checkout all branches and tags

      - name: "Use NodeJS 16.16.0" # Setup node using version 16.16.0
        uses: actions/setup-node@v3 # Public action
        with: 
          node-version: '16.16.0'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@bitsongjs'

      - name: Install dependencies
        run: | # Install and link dependencies
          npm install --global yarn
          yarn install --frozen-lockfile
          yarn bootstrap
          yarn build

      - name: "Setup yarn configs" # Add our registry to npm config
        run: | # Custom action
          yarn config set @bitsongjs:registry=https://npm.pkg.github.com
          yarn config set "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}"

      - name: "Version and publish" # Interesting step
        env:
          GH_TOKEN: ${{ secrets.GITHUB_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          if [ ${{ github.base_ref }} = dev ]; then
            npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
          else
            npx lerna version --conventional-commits --conventional-graduate --yes
          fi

          npx lerna publish from-git --yes